import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#FFF9F5',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    marginBottom: 8,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: 0.2,
  },
  bellBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  petCard: {
    borderRadius: 22,
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    overflow: 'hidden',
    marginBottom: 20,
    position: 'relative',
  },
  vitalityBadge: {
    position: 'absolute',
    top: 14,
    left: 14,
    zIndex: 2,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  vitalityText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  petImageWrap: {
    height: 230,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF0EB',
  },
  petImage: {
    width: 180,
    height: 180,
  },
  barsRow: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: 22,
  },
  barBlock: {
    flex: 1,
  },
  barLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 7,
  },
  barLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#777',
    letterSpacing: 0.4,
    flex: 1,
  },
  barValue: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  barTrack: {
    height: 9,
    borderRadius: 5,
    backgroundColor: '#f0e6e0',
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    borderRadius: 5,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: 0.5,
  },
  demoToggle: {
    fontSize: 11,
    fontWeight: '600',
    color: '#999',
  },
  focusCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 18,
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    marginBottom: 24,
  },
  focusLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  focusLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#777',
    letterSpacing: 0.3,
  },
  focusValue: {
    fontSize: 22,
    fontWeight: '900',
    color: '#1a1a1a',
  },
  focusRight: {
    alignItems: 'flex-end',
    gap: 5,
  },
  statusPill: {
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: 10,
  },
  limitText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#999',
  },
  powerList: {
    gap: 10,
    marginBottom: 24,
  },
  powerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 15,
    borderRadius: 16,
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
  },
  powerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    flex: 1,
  },
  powerIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#FFF0EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  powerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  powerMeta: {
    fontSize: 11,
    fontWeight: '600',
    color: '#999',
    marginTop: 2,
  },
  badgesRow: {
    flexDirection: 'row',
    gap: 10,
  },
  badgeCard: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 6,
    borderRadius: 16,
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    gap: 6,
  },
  badgeName: {
    fontSize: 10,
    fontWeight: '700',
    color: '#777',
    textAlign: 'center',
  },
});