import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#B83F3F',
  },
  keyboard: {
    flex: 1,
    backgroundColor: '#FFF9F5',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingTop: 40,
    paddingBottom: 40,
    justifyContent: 'center',
  },
  logoSection: {
    alignItems: 'center',
    marginBottom: 48,
  },
  logoCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#FFF0EB',
    borderWidth: 2.5,
    borderColor: '#B83F3F',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
  },
  appTitle: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 18,
    color: '#1a1a1a',
    marginBottom: 8,
  },
  appSubtitle: {
    fontSize: 14,
    color: '#777',
    textAlign: 'center',
    lineHeight: 20,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#777',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#1a1a1a',
    marginBottom: 20,
  },
  passwordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    borderRadius: 14,
    marginBottom: 10,
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#1a1a1a',
  },
  showHideBtn: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  showHideText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#B83F3F',
  },
  forgotBtn: {
    alignSelf: 'flex-end',
    marginBottom: 32,
  },
  forgotText: {
    fontSize: 13,
    color: '#999',
  },
  loginBtn: {
    backgroundColor: '#B83F3F',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#B83F3F',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  loginBtnText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#fff',
  },
  orRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  orLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#f0e6e0',
  },
  orText: {
    marginHorizontal: 14,
    fontSize: 12,
    color: '#999',
    fontWeight: '600',
  },
  googleBtn: {
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 28,
  },
  googleBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  signupRow: {
    alignItems: 'center',
  },
  signupText: {
    fontSize: 14,
    color: '#777',
  },
  signupLink: {
    color: '#B83F3F',
    fontWeight: '700',
  },
});