import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF9F5',
  },
  topSection: {
    paddingHorizontal: 28,
    marginBottom: 12,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '900',
    color: '#1a1a1a',
    letterSpacing: -0.6,
    textAlign: 'center',
    lineHeight: 33,
  },
  pixelTitle: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 16,
    color: '#FF6B6B',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  accentLine: {
    width: 36,
    height: 3,
    backgroundColor: '#FF6B6B',
    borderRadius: 2,
    marginTop: 12,
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 14.5,
    color: '#777',
    lineHeight: 20,
    textAlign: 'center',
    paddingHorizontal: 10,
  },
  stage: {
    height: 340,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrow: {
    position: 'absolute',
    top: '32%',
    zIndex: 10,
    padding: 10,
  },
  arrowLeft: {
    left: 8,
  },
  arrowRight: {
    right: 8,
  },
  petWrapper: {
    alignItems: 'center',
    width: width * 0.75,   // ← this is what was missing
  },
  circleFrame: {
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: '#FFF0EB',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 3,
    borderColor: '#FF6B6B',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  petImage: {
    width: '88%',
    height: '88%',
  },
  petTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FF6B6B',
    letterSpacing: 1.1,
    marginBottom: 4,
  },
  petName: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 16,
    color: '#1a1a1a',
    marginBottom: 8,
  },
  petDescription: {
    fontSize: 13.5,
    color: '#666',
    textAlign: 'center',
    lineHeight: 19,
    paddingHorizontal: 10,
  },
  dots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    marginTop: 6,
    marginBottom: 28,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#e0d5cf',
  },
  dotActive: {
    backgroundColor: '#FF6B6B',
    width: 22,
  },
  nameSection: {
    paddingHorizontal: 24,
    marginBottom: 18,
    marginTop: 4,
  },
  nameLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 10,
  },
  nameInput: {
    height: 50,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    borderRadius: 14,
    paddingHorizontal: 16,
    fontSize: 15,
    color: '#1a1a1a',
    backgroundColor: '#fff',
  },
  startButton: {
    marginHorizontal: 24,
    height: 54,
    backgroundColor: '#FF6B6B',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.28,
    shadowRadius: 12,
    elevation: 6,
  },
  startButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },
});