import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // ========== LANDSCAPE ==========
  landscapeContainer: {
    flex: 1,
    backgroundColor: '#FFF9F5',
  },
  landscapeRow: {
    flex: 1,
    flexDirection: 'row',
    gap: 14,
  },
  landscapePetCard: {
    width: '46%',
    backgroundColor: '#FFF0EB',
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 16,
    zIndex: 10,
  },
  landscapePetControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },
  landscapePetCircle: {
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: '#FFF7F2',
    borderWidth: 3,
    borderColor: '#E8B923',
    justifyContent: 'center',
    alignItems: 'center',
  },
  landscapeDots: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 22,
  },
  landscapeInfoCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    paddingHorizontal: 18,
    paddingVertical: 18,
    justifyContent: 'space-between',
    zIndex: 5,
  },
  landscapeTitlePill: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFF0EB',
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: 20,
    marginBottom: 10,
  },
  landscapeTitlePillText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#B83F3F',
    letterSpacing: 0.6,
  },
  landscapePetName: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 16,
    color: '#1a1a1a',
    marginBottom: 10,
  },
  landscapeDescriptionBox: {
    backgroundColor: '#FFF9F5',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
  },
  landscapeDescriptionText: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  landscapeNameLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 8,
  },
  landscapeNameInput: {
    height: 46,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    borderRadius: 14,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#1a1a1a',
    backgroundColor: '#FFF9F5',
    marginBottom: 12,
  },
  landscapeStartButton: {
    height: 48,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  landscapeStartButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },

  // ========== PORTRAIT ==========
  portraitContainer: {
    flex: 1,
    backgroundColor: '#FFF9F5',
  },
  cinematicFlash: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#E8B923',
    zIndex: 200,
  },
  portraitTopText: {
    paddingHorizontal: 28,
    alignItems: 'center',
    marginBottom: 10,
    zIndex: 1,
  },
  portraitHeaderTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#1a1a1a',
    letterSpacing: -0.5,
    textAlign: 'center',
    lineHeight: 30,
  },
  portraitPixelTitle: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 15,
    color: '#B83F3F',
    textAlign: 'center',
    marginTop: 8,
  },
  portraitStage: {
    height: 280,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    zIndex: 50,
  },
  portraitArrowLeft: {
    position: 'absolute',
    left: 16,
    zIndex: 60,
  },
  portraitArrowRight: {
    position: 'absolute',
    right: 16,
    zIndex: 60,
  },
  portraitPetCircle: {
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: '#FFF7F2',
    borderWidth: 3.5,
    borderColor: '#E8B923',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#E8B923',
    shadowOffset: { width: 0, height: 0 },
  },
  portraitDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 18,
    zIndex: 1,
  },
  portraitInfoCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    paddingHorizontal: 24,
    paddingTop: 24,
    zIndex: 10,
  },
  portraitTitlePill: {
    alignSelf: 'center',
    backgroundColor: '#FFF0EB',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    marginBottom: 12,
  },
  portraitTitlePillText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#B83F3F',
    letterSpacing: 0.8,
  },
  portraitPetName: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 20,
    color: '#1a1a1a',
    textAlign: 'center',
    marginBottom: 14,
  },
  portraitDescriptionBox: {
    backgroundColor: '#FFF9F5',
    borderRadius: 16,
    padding: 14,
    marginBottom: 22,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
  },
  portraitDescriptionText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    lineHeight: 20,
  },
  portraitNameLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 10,
  },
  portraitNameInput: {
    height: 50,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    borderRadius: 14,
    paddingHorizontal: 16,
    fontSize: 15,
    color: '#1a1a1a',
    backgroundColor: '#FFF9F5',
    marginBottom: 16,
  },
  portraitStartButton: {
    height: 54,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  portraitStartButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },

  // ========== SHARED ==========
  dot: {
    height: 8,
    borderRadius: 4,
  },
  petAnimatedWrap: {
    alignItems: 'center',
  },
});