import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1A1210',
  },
  header: {
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 8,
  },
  headerTitle: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 14,
    color: '#F5E6D3',
    textAlign: 'center',
    marginBottom: 8,
  },
  headerSub: {
    fontSize: 14,
    color: '#C9B8A8',
    textAlign: 'center',
    lineHeight: 20,
  },
  stage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  petAnimatedWrap: {
    alignItems: 'center',
    zIndex: 100,
  },
  // Clean circle — overflow hidden kills hex/gif edge artifacts
  petCircle: {
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: '#2A1F1C',
    borderWidth: 3.5,
    borderColor: '#B83F3F',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  petImage: {
    width: '85%',
    height: '85%',
  },
  petName: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 16,
    color: '#F5E6D3',
    textAlign: 'center',
    marginTop: 18,
  },
  petMeta: {
    fontSize: 13,
    color: '#E07A6A',
    marginTop: 6,
    fontWeight: '700',
  },
  dropZone: {
    marginHorizontal: 20,
    borderRadius: 16,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#B83F3F',
    backgroundColor: '#2A1F1C',
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropZoneActive: {
    backgroundColor: '#3D1F1C',
    borderColor: '#E07A6A',
    borderStyle: 'solid',
  },
  dropText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#F5E6D3',
  },
  dropHint: {
    fontSize: 12,
    color: '#BBAEA0',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 4,
  },

  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.72)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#2A1F1C',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 2,
    borderColor: '#5A4038',
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  sheetTitle: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 12,
    color: '#F5E6D3',
    textAlign: 'center',
    marginBottom: 6,
  },
  sheetSub: {
    fontSize: 13,
    color: '#C9B8A8',
    textAlign: 'center',
    marginBottom: 16,
  },
  stone: {
    backgroundColor: '#1A1210',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#5A4038',
    padding: 16,
    marginBottom: 14,
  },
  stoneName: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 13,
    color: '#E8D5C4',
    textAlign: 'center',
    marginBottom: 6,
  },
  stoneLine: {
    fontSize: 13,
    color: '#C9B8A8',
    textAlign: 'center',
    marginBottom: 4,
  },
  stoneDate: {
    fontSize: 12,
    color: '#BBAEA0',
    textAlign: 'center',
    marginTop: 8,
  },
  label: {
    fontSize: 12,
    fontWeight: '800',
    color: '#BBAEA0',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#1A1210',
    borderWidth: 1.5,
    borderColor: '#3D2E2A',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#F5E6D3',
    fontSize: 15,
    minHeight: 88,
    textAlignVertical: 'top',
    marginBottom: 16,
  },
  buryBtn: {
    backgroundColor: '#B83F3F',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 10,
  },
  buryBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },
  cancelBtn: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  cancelText: {
    color: '#BBAEA0',
    fontSize: 14,
    fontWeight: '700',
  },
});