import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // Shared
  safe: {
    flex: 1,
    backgroundColor: '#B83F3F',
  },

  // ========== LANDSCAPE ==========
  landscapeRow: {
    flex: 1,
    flexDirection: 'row',
    padding: 14,
    gap: 14,
  },
  landscapeLeft: {
    width: '42%',
    gap: 12,
  },
  landscapeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  landscapeHeaderTitle: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 11,
    color: '#1a1a1a',
  },
  landscapeLevelCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  landscapeLevelTitle: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 13,
    color: '#1a1a1a',
  },
  landscapeLevelSub: {
    fontSize: 12,
    color: '#777',
    marginTop: 4,
  },
  landscapePillsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  landscapeImageBox: {
    width: 56,
    height: 56,
    borderRadius: 14,
    backgroundColor: '#FFF7F2',
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  landscapeStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  landscapeStatCard: {
    width: '47%',
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    padding: 12,
  },
  landscapeStatLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  landscapeStatLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#999',
  },
  landscapeStatValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  landscapeRightScroll: {
    flex: 1,
  },
  landscapeRightContent: {
    gap: 12,
    paddingBottom: 20,
  },
  landscapeCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    padding: 14,
  },
  landscapeCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  landscapeCardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  landscapeCardTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  landscapeMonthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  landscapeMonthText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  dayHeaders: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  dayHeaderCell: {
    flex: 1,
    alignItems: 'center',
  },
  dayHeaderText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#999',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarCell: {
    width: `${100 / 7}%` as any,
    aspectRatio: 1,
    padding: 2,
  },
  calendarCellInner: {
    flex: 1,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  calendarDayText: {
    fontSize: 11,
    fontWeight: '600',
  },
  legendRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 2,
  },
  legendText: {
    fontSize: 9,
    fontWeight: '600',
    color: '#777',
  },
  intensityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  healthyPill: {
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  healthyPillText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#16a34a',
  },
  intensitySub: {
    fontSize: 11,
    color: '#999',
    marginBottom: 10,
  },
  barChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 110,
    gap: 6,
  },
  barCol: {
    flex: 1,
    alignItems: 'center',
  },
  barFill: {
    width: '80%',
    borderRadius: 6,
    minHeight: 6,
  },
  barLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#777',
    marginTop: 6,
  },

  // ========== PORTRAIT ==========
  portraitScroll: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 40,
  },
  portraitHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  portraitHeaderTitle: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 13,
    color: '#1a1a1a',
  },
  portraitLevelCard: {
    backgroundColor: '#fff',
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 18,
  },
  portraitLevelTitle: {
    fontFamily: 'PressStart2P_400Regular',
    fontSize: 14,
    color: '#1a1a1a',
  },
  portraitLevelSub: {
    fontSize: 13,
    color: '#777',
    marginTop: 4,
  },
  portraitPillsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  portraitImageBox: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: '#FFF7F2',
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  portraitCard: {
    backgroundColor: '#fff',
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    padding: 16,
    marginBottom: 18,
  },
  portraitCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  portraitCardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  portraitCardTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  portraitMonthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  portraitMonthText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  portraitDayHeaderText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#999',
  },
  portraitCalendarCell: {
    width: `${100 / 7}%` as any,
    aspectRatio: 1,
    padding: 3,
  },
  portraitCalendarCellInner: {
    flex: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  portraitCalendarDayText: {
    fontSize: 12,
    fontWeight: '600',
  },
  portraitLegendRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 14,
    flexWrap: 'wrap',
    gap: 6,
  },
  portraitLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  portraitLegendDot: {
    width: 11,
    height: 11,
    borderRadius: 3,
  },
  portraitLegendText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#777',
  },
  portraitStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 11,
    marginBottom: 18,
  },
  portraitStatCard: {
    width: '47.5%',
    backgroundColor: '#fff',
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    padding: 14,
  },
  portraitStatLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  portraitStatLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#999',
  },
  portraitStatValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  portraitIntensityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  portraitHealthyPill: {
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  portraitHealthyPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#16a34a',
  },
  portraitIntensitySub: {
    fontSize: 12,
    color: '#999',
    marginBottom: 14,
  },
  portraitBarChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 130,
    gap: 8,
  },
  portraitBarFill: {
    width: '75%',
    borderRadius: 7,
    minHeight: 8,
  },
  portraitBarLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#777',
    marginTop: 8,
  },
  criticalRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 14,
  },
  criticalIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#FFF0EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  criticalTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1a1a1a',
    marginBottom: 4,
  },
  criticalBody: {
    fontSize: 13,
    color: '#666',
    lineHeight: 19,
  },
  restoreBtn: {
    backgroundColor: '#FF6B6B',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  restoreBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  previousLosses: {
    borderWidth: 1.5,
    borderColor: '#f0e6e0',
    borderStyle: 'dashed',
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFF7F2',
  },
  previousLossesLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  previousLossesText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#555',
  },
  previousLossesLink: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FF6B6B',
  },

  // Shared pills
  streakPill: {
    backgroundColor: '#FFF0EB',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  streakPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FF6B6B',
  },
  hpPill: {
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  hpPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#16a34a',
  },
  streakPillLandscape: {
    backgroundColor: '#FFF0EB',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  streakPillTextLandscape: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FF6B6B',
  },
  hpPillLandscape: {
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  hpPillTextLandscape: {
    fontSize: 10,
    fontWeight: '700',
    color: '#16a34a',
  },
});